#!/bin/bash
# CWOP-SDLC Customer Display - Raspberry Pi Zero 2 W Setup
# Configures Pi Zero 2 W with HyperPixel 4 Square as a kiosk display.
# Idempotent: safe to re-run at any time.

set -euo pipefail

# ── Colors ──
BOLD='\033[1m'
DIM='\033[2m'
CYAN='\033[36m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
RESET='\033[0m'

TOTAL=10
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CWOP_DIR="/home/pi/cwop-sdlc"

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}+-----------------------------------------------+${RESET}"
  echo -e "${CYAN}${BOLD}|    CWOP-SDLC  Customer Display Setup          |${RESET}"
  echo -e "${CYAN}${BOLD}|    Raspberry Pi Zero 2 W + HyperPixel 4 Sq    |${RESET}"
  echo -e "${CYAN}${BOLD}+-----------------------------------------------+${RESET}"
  echo ""
}

step() {
  echo -e "\n${CYAN}[$1/$TOTAL]${RESET} ${BOLD}$2${RESET}"
}

ok() {
  echo -e "  ${GREEN}[ok]${RESET} $1"
}

warn() {
  echo -e "  ${YELLOW}[warn]${RESET} $1"
}

fail() {
  echo -e "  ${RED}[fail]${RESET} $1"
  exit 1
}

banner

# ── Step 1: Platform Check ──
step 1 "Verifying platform..."

ARCH=$(uname -m)
if [[ "$ARCH" != "aarch64" && "$ARCH" != "armv6l" && "$ARCH" != "armv7l" ]]; then
  fail "This script is designed for Raspberry Pi (expected ARM architecture, got $ARCH)."
fi
ok "Platform: $ARCH"

if [ "$(id -u)" -eq 0 ]; then
  fail "Do not run this script as root. Run as the 'pi' user; sudo will be used where needed."
fi
ok "Running as user: $(whoami)"

# ── Step 2: System Update ──
step 2 "Updating system packages..."

sudo apt update && sudo apt upgrade -y
ok "System updated"

# ── Step 3: Install Display and Kiosk Packages ──
step 3 "Installing display and kiosk packages..."

sudo apt install -y \
  avahi-utils \
  xserver-xorg-core \
  xinit \
  x11-xserver-utils \
  unclutter \
  midori
ok "Packages installed"

# ── Step 4: Configure HyperPixel 4 Square ──
step 4 "Configuring HyperPixel 4 Square display..."

BOOT_CONFIG="/boot/config.txt"
# Some Pi OS versions use /boot/firmware/config.txt
if [ -f "/boot/firmware/config.txt" ]; then
  BOOT_CONFIG="/boot/firmware/config.txt"
fi

OVERLAY_LINE="dtoverlay=vc4-kms-dpi-hyperpixel4sq"
if grep -q "$OVERLAY_LINE" "$BOOT_CONFIG" 2>/dev/null; then
  ok "HyperPixel overlay already configured in $BOOT_CONFIG"
else
  echo "" | sudo tee -a "$BOOT_CONFIG" > /dev/null
  echo "# HyperPixel 4 Square display" | sudo tee -a "$BOOT_CONFIG" > /dev/null
  echo "$OVERLAY_LINE" | sudo tee -a "$BOOT_CONFIG" > /dev/null
  ok "HyperPixel overlay added to $BOOT_CONFIG"
fi

# ── Step 5: Configure WiFi ──
step 5 "Configuring WiFi connection to cwop-tech..."

echo ""
read -sp "  Enter WiFi password for the cwop-tech network: " WIFI_PASSWORD
echo ""

if [ ${#WIFI_PASSWORD} -lt 8 ]; then
  fail "WiFi password must be at least 8 characters."
fi

WPA_CONF="/etc/wpa_supplicant/wpa_supplicant.conf"
sudo tee "$WPA_CONF" > /dev/null <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
    ssid="cwop-tech"
    psk="${WIFI_PASSWORD}"
    key_mgmt=WPA-PSK
}
EOF

sudo chmod 600 "$WPA_CONF"
ok "WiFi configured to connect to cwop-tech"

# ── Step 6: Configure Gateway Connection ──
step 6 "Configuring gateway connection..."

echo ""
DEFAULT_GATEWAY="http://10.42.0.1:18790"
read -p "  Gateway URL [${DEFAULT_GATEWAY}]: " GATEWAY_URL
GATEWAY_URL="${GATEWAY_URL:-$DEFAULT_GATEWAY}"

echo ""
read -p "  CWOP API key (from technician handheld setup): " CWOP_API_KEY

if [ -z "$CWOP_API_KEY" ]; then
  fail "API key is required. Run setup-pi5.sh on the technician handheld first."
fi

ok "Gateway: $GATEWAY_URL"

# ── Step 7: Create Environment File ──
step 7 "Writing environment file..."

ENV_FILE="$CWOP_DIR/.env"
mkdir -p "$CWOP_DIR"

cat > "$ENV_FILE" <<EOF
# CWOP-SDLC Customer Display Environment
# Generated by setup-zero2w.sh on $(date -Iseconds)
CWOP_GATEWAY_URL=${GATEWAY_URL}
CWOP_API_KEY=${CWOP_API_KEY}
EOF

chmod 600 "$ENV_FILE"
ok "Environment file written to $ENV_FILE"

# ── Step 8: Configure Auto-Login ──
step 8 "Configuring auto-login on tty1..."

AUTOLOGIN_DIR="/etc/systemd/system/getty@tty1.service.d"
sudo mkdir -p "$AUTOLOGIN_DIR"
sudo tee "$AUTOLOGIN_DIR/autologin.conf" > /dev/null <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I \$TERM
EOF

ok "Auto-login configured for user pi on tty1"

# Add startx to .bash_profile if not already present
BASH_PROFILE="/home/pi/.bash_profile"
STARTX_LINE='[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx -- -nocursor'

if ! grep -qF "$STARTX_LINE" "$BASH_PROFILE" 2>/dev/null; then
  cat >> "$BASH_PROFILE" <<EOF

# Auto-start X on tty1 for kiosk mode
${STARTX_LINE}
EOF
  ok "startx added to $BASH_PROFILE"
else
  ok "startx already configured in $BASH_PROFILE"
fi

# ── Step 9: Install Kiosk Service and Script ──
step 9 "Installing kiosk service and launcher..."

# Ensure the device scripts directory exists in the target location
DISPLAY_DIR="$CWOP_DIR/devices/customer-display"
mkdir -p "$DISPLAY_DIR"

# Copy kiosk.sh to the target location
cp "$SCRIPT_DIR/kiosk.sh" "$DISPLAY_DIR/kiosk.sh"
chmod +x "$DISPLAY_DIR/kiosk.sh"
ok "kiosk.sh installed to $DISPLAY_DIR/"

# Install systemd service
sudo cp "$SCRIPT_DIR/cwop-kiosk.service" /etc/systemd/system/cwop-kiosk.service
sudo systemctl daemon-reload
sudo systemctl enable cwop-kiosk.service
ok "cwop-kiosk.service installed and enabled"

# ── Step 10: Create .xinitrc for Kiosk ──
step 10 "Creating X11 init configuration..."

XINITRC="/home/pi/.xinitrc"
cat > "$XINITRC" <<EOF
#!/bin/bash
# CWOP Kiosk X11 init
exec /home/pi/cwop-sdlc/devices/customer-display/kiosk.sh
EOF
chmod +x "$XINITRC"
ok ".xinitrc configured for kiosk mode"

# ── Summary ──
echo ""
echo -e "${GREEN}${BOLD}+-----------------------------------------------+${RESET}"
echo -e "${GREEN}${BOLD}|         Setup Complete!                        |${RESET}"
echo -e "${GREEN}${BOLD}+-----------------------------------------------+${RESET}"
echo ""
echo -e "  ${BOLD}WiFi Network:${RESET}      cwop-tech"
echo -e "  ${BOLD}Gateway URL:${RESET}       $GATEWAY_URL"
echo -e "  ${BOLD}Display:${RESET}           HyperPixel 4 Square (720x720)"
echo ""
echo -e "  ${BOLD}Services installed:${RESET}"
echo -e "    cwop-kiosk.service  - Fullscreen kiosk browser"
echo ""
echo -e "  ${BOLD}Next steps:${RESET}"
echo -e "    1. Ensure the technician handheld (Pi 5) is powered on"
echo -e "    2. Reboot this device:  ${CYAN}sudo reboot${RESET}"
echo -e "    3. The display should auto-start in kiosk mode"
echo -e "    4. To exit kiosk mode: press ${CYAN}Ctrl+Alt+F2${RESET} for a console"
echo ""
echo -e "  ${BOLD}Troubleshooting:${RESET}"
echo -e "    ${CYAN}sudo systemctl status cwop-kiosk${RESET}"
echo -e "    ${CYAN}journalctl -u cwop-kiosk -f${RESET}"
echo ""
